### ISSUE TITLE
Remove client timeout handling and use SDK timeout support instead

### ISSUE THREAD

**Issue by davidkel** [davidkel/fabric-chaos-testing#10]
We should move our test client to use the official timeouts. What would be good to test as well would be that the client doesn't remain hanging on exit (it would mean changing the client to just exit the loop when ctrl-c is received but not doing a process.exit() ) if timeouts or problems are hit

**Comment by davidkel** [comment]
Taken from the sample, the code shows
```
   const gateway = connect({
        client,
        identity: await newIdentity(),
        signer: await newSigner(),
        // Default timeouts for different gRPC calls
        evaluateOptions: () => {
            return { deadline: Date.now() + 5000 }; // 5 seconds
        },
        endorseOptions: () => {
            return { deadline: Date.now() + 15000 }; // 15 seconds
        },
        submitOptions: () => {
            return { deadline: Date.now() + 5000 }; // 5 seconds
        },
        commitStatusOptions: () => {
            return { deadline: Date.now() + 60000 }; // 1 minute
        },
        chaincodeEventsOptions: () => {
            return { deadline: Date.now() + 60000 }; // 1 minute
        },
    });
    ```

**Comment by davidkel** [comment]
Currently the client has no timeout control on endorse, evaluate or submit so we can take advantage of the timeout support in the api now. We can remove our timeout implementation around getting status now and take advantage of the sdk timeout, however we should leave our timeout processing for chaincode events in place. The chaincode event options isn't applicable to our implementation.

**Comment by sapthasurendran** [comment]
```
message":"9 FAILED_PRECONDITION: context deadline exceeded Details: []"
message":"4 DEADLINE_EXCEEDED: Deadline exceeded Details: []"
```
@bestbeforetoday  Could you please help me differentiate these error messages during commit timeout .

**Comment by davidkel** [comment]
#54
